#!/bin/sh -ex
NGINX_DAV_EXT_MODULE_VERSION="$(grep --perl-regexp '(?<=nginx_dav_ext_module_version_).+$' /etc/hosts --max-count 1 --only-matching)"
printf 'https://github.com/arut/nginx-dav-ext-module/archive/refs/tags/v%s.tar.gz\n' "$NGINX_DAV_EXT_MODULE_VERSION" >"$(dirname -- "$0")/source"
